### ISSUE TITLE
SELFIE REDEMPTION - Redemption Clause

### ISSUE THREAD

**Issue by statiamarieshillingford** [guldcoin/Documents-guld#2]
"Redemption
4.1 The rate for a selfie is twenty (20) ISYSD tokens per one (1) hour. A selfie can be purchased in three (3) minute increments The minimum purchase is one (1) increment."

What is your interpretation of this clause? 
Is it that one increment is worth 3 minutes?
And that 3 minutes is the amount of time blocked off per selfie?

**Comment by polarweasel** [comment]
Probably makes more sense as “1 ISYSD token per 3-minute selfie session”...

**Comment by isysd** [comment]
It is always given as an hourly rate in the other contracts, which is pro-rated in chunks of the increment. I.e. if the hourly rate is 20 ISYSD, and the minimum increment is 3 minutes, the payments will be incremented in 1 ISYSD chunks. I parameterized the contract so I think it is in line with the others now :)
