### ISSUE TITLE
SHAVE BEARD REDEMPTION 

### ISSUE THREAD

**Issue by statiamarieshillingford** [guldcoin/Documents-guld#3]
For this contract instead of making a separate module for "you shave my beard" vs "shave my beard", I've made it a variable  under the PURPOSE OF THE AGREEMENT.

Also the CUSTOM_RATE is a variable under the REDEMPTION clause for that same reason.

**Comment by statiamarieshillingford** [comment]
PARTY?_NAME =VARIABLE for who shaves the beard.

**Comment by isysd** [comment]
Awesome! I loved that. Changed it to SHAVER though. :dagger:
